import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { toJSONSchema, type ZodType } from 'zod'

import {
  appConfigSchema,
  assetManifestSchema,
  contentManifestSchema,
  courseSchema,
  learnerSeedSchema,
  primitiveBaseSchema,
} from '../src/content/schema/index.ts'
import {
  assessmentPrimitiveTypes,
  contentPrimitiveTypes,
  dicomPrimitiveTypes,
  primitiveTypes,
} from '../src/content/primitiveTypes.ts'
import { primitiveContentSchemas } from '../src/content/schema/primitives/index.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputDirectory = resolve(root, 'schemas')

const schemas: Record<string, ZodType> = {
  'content-manifest': contentManifestSchema,
  'app-config': appConfigSchema,
  course: courseSchema,
  'learner-seed': learnerSeedSchema,
  'asset-manifest': assetManifestSchema,
  primitive: primitiveBaseSchema,
}

await mkdir(outputDirectory, { recursive: true })

for (const [name, schema] of Object.entries(schemas)) {
  const jsonSchema = toJSONSchema(schema, {
    target: 'draft-7',
    unrepresentable: 'any',
  })
  await writeFile(
    resolve(outputDirectory, `${name}.schema.json`),
    `${JSON.stringify(jsonSchema, null, 2)}\n`,
  )
}

const document = `# Content schema v0.1

Generated by \`npm run schema:export\`. Runtime Zod schemas remain authoritative.

## Generated documents

${Object.keys(schemas)
  .map((name) => `- \`schemas/${name}.schema.json\``)
  .join('\n')}

These six JSON Schema documents describe the exported document envelopes. In particular,
\`schemas/primitive.schema.json\` is the shared forward-compatible primitive envelope; the strict
per-type content contracts are enforced by the runtime Zod schemas listed below and are not emitted
as separate JSON Schema files.

## Primitive registry

The canonical registry contains ${primitiveTypes.length} strict primitive types: ${
  primitiveTypes.length - dicomPrimitiveTypes.length
} standard types and ${dicomPrimitiveTypes.length} DICOM types.

### Content (${contentPrimitiveTypes.length})

${contentPrimitiveTypes.map((type) => `- \`${type}\``).join('\n')}

### Assessment (${assessmentPrimitiveTypes.length})

${assessmentPrimitiveTypes.map((type) => `- \`${type}\``).join('\n')}

### Domain

- \`scenario\` (strict standard primitive)
${dicomPrimitiveTypes.map((type) => `- \`${type}\` (strict DICOM primitive)`).join('\n')}

## Strict primitive schemas (${Object.keys(primitiveContentSchemas).length})

${Object.keys(primitiveContentSchemas)
  .map((type) => `- \`${type}\``)
  .join('\n')}

The four DICOM types require a typed DICOM series asset and strict mode-specific content. Unknown
types are retained with a warning so development playback can render the unsupported fallback.
Every lesson primitive and challenge item passes through the same parser and semantic validation.

## Shared primitive envelope

- IDs use lowercase letters, digits, underscores and hyphens.
- Completion supports \`viewed\`, \`answer\`, \`minimum_interactions\`, \`explored\`,
  \`media_progress\`, \`measurement\`, \`outcome\`, \`interacted\` and \`correct_order\`, while
  preserving unknown non-empty modes for forward-compatible fallback.
- Scoring supports a positive weight plus optional non-negative XP and configured difficulty.
- Feedback supports retry, maximum attempts, correct/incorrect copy and hints.
- Rewards, sources and positive-duration countdown/elapsed timers are optional.

## Semantic validation

- Course visibility defaults to \`learner\`; \`internal\` courses remain addressable but are excluded
  from learner-facing catalog collections.
- Primitive IDs must be unique within each lesson or challenge.
- Primitive concept, badge reward, declared asset and typed content-asset references must resolve.
- Typed content assets must match the asset type declared by their primitive schema.
- Timers are accepted only on registered assessment types listed by the content layer.
- Scenario graphs require unique IDs, a valid start, resolved transitions, acyclic outcome-ending
  paths and no unreachable nodes; paths outside two to four decisions produce warnings.
- Formula TeX is parsed in Node with KaTeX and mhchem during content validation.
- DICOM slice ranges, preset/tool references, calibrated measurements and reference-line geometry
  are validated against series metadata.
- Gamification XP keys, levels, star thresholds, weekly-goal defaults and mastery weights are
  strictly configured.
- Badge criteria and weekly challenge progress rules resolve referenced courses, lessons,
  challenges, concepts, primitive types and primitive rewards.

## Gamification and learner state

- Badge criteria support completed lessons/courses, perfect lessons, streak days, weekly goals,
  challenge completions, first-attempt correctness and authored primitive rewards.
- Badge progress is derived from learner facts; persisted badge records contain unlock timestamps.
- Learner state version 3 stores reward idempotency, challenge periods, counters, the active reward
  run, latest activity/question results, celebrations and an abstract digital reward ledger.
- XP, star, mastery, streak and period rules are reduced from typed learner events.

## Asset manifest

Asset types are \`image\`, \`video\`, \`audio\`, \`dicom\`, \`document\` and \`text\`. DICOM entries
require slice count, matrix, pixel spacing, slice thickness and calibration metadata. Other entries
may include \`mimeType\`, positive integer \`width\` and \`height\`, and non-negative
\`sizeBytes\`.

## Versioning

- Content schema: \`0.1\`
- Course documents also include an independent \`courseVersion\`.
- Persisted learner state is version 3 and migrates older snapshots.
- In-flight activity sessions are persisted independently at version 2; version 1 sessions restart.
`

await writeFile(resolve(root, 'docs/CONTENT_SCHEMA.md'), document)
console.log(`Exported ${Object.keys(schemas).length} schemas to ${outputDirectory}`)
