import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { toJSONSchema, type ZodType } from 'zod'

import {
  appConfigSchema,
  assetManifestSchema,
  contentManifestSchema,
  courseSchema,
  learnerSeedSchema,
  primitiveBaseSchema,
} from '../src/content/schema/index.ts'
import { primitiveTypes } from '../src/content/primitiveTypes.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputDirectory = resolve(root, 'schemas')

const schemas: Record<string, ZodType> = {
  'content-manifest': contentManifestSchema,
  'app-config': appConfigSchema,
  course: courseSchema,
  'learner-seed': learnerSeedSchema,
  'asset-manifest': assetManifestSchema,
  primitive: primitiveBaseSchema,
}

await mkdir(outputDirectory, { recursive: true })

for (const [name, schema] of Object.entries(schemas)) {
  const jsonSchema = toJSONSchema(schema, {
    target: 'draft-7',
    unrepresentable: 'any',
  })
  await writeFile(
    resolve(outputDirectory, `${name}.schema.json`),
    `${JSON.stringify(jsonSchema, null, 2)}\n`,
  )
}

const document = `# Content schema v0.1

Generated by \`npm run schema:export\`. Runtime Zod schemas remain authoritative.

## Generated documents

${Object.keys(schemas)
  .map((name) => `- \`schemas/${name}.schema.json\``)
  .join('\n')}

## Primitive types

${primitiveTypes.map((type) => `- \`${type}\``).join('\n')}

Phase 1 strictly validates \`rich_text\`, \`image\` and \`multiple_choice\` content. Registered future
types retain record-shaped content until their implementation phase. Unknown types are retained with a
warning so content can fail gracefully at rendering time.

## Versioning

- Content schema: \`0.1\`
- Course documents also include an independent \`courseVersion\`.
- Persisted learner state uses an integer \`stateVersion\` and migrations.
`

await writeFile(resolve(root, 'docs/CONTENT_SCHEMA.md'), document)
console.log(`Exported ${Object.keys(schemas).length} schemas to ${outputDirectory}`)
